name: Build Preview Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    name: Build Preview
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Quartz repository
        run: |
          git clone https://github.com/jackyzha0/quartz.git quartz-repo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd quartz-repo
          npm i

      - name: Run Quartz setup
        run: |
          cd quartz-repo
          npx quartz create
          rm -rf content

      - name: Move markdown files from src to content
        run: |
          mkdir -p quartz-repo/content
          ls
          mv src/*.md quartz-repo/content/

      - name: Check types and style
        run: |
          cd quartz-repo
          npm run check

      - name: Build Quartz
        run: |
          cd quartz-repo
          npx quartz build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: quartz-repo/public
          single-commit: true
          branch: gh-pages
          target_folder: /

